import java.util.* ;
import java.util.Random ;
public class task1{
    public static void main(String args[])
    {
        Scanner sc = new Scanner(System.in);
        Random rand = new Random();
        int score1 = 0 , score2 = 0 , score3 = 0 ;
        System.out.println("*************   NUMBER GUESSING GAME  *************");
        System.out.println(" Welcome !! you are playing a number guessing game");
        System.out.println("\n                        RULES");
        System.out.println("1.) The game is divided into 3 rounds ");
        System.out.println("2.)You will get 5 chances to guess a number in each round");
        System.out.println("3.) (a) If your number and number generated by us is equal then you get 1 Point");
        System.out.println("    (b) If it is nit equal you will get 0 points");
        System.out.println("If your answer is far from answer by 40 or more value them you will get message ---> you are too far from generated number");
        System.out.println("If your answer is far from answer between 40 and 10 value them you will get message ---> you are neither too close nor too far from generated number");
        System.out.println("If your answer is far from answer between 10 and 1 value them you will get message ---> you are too close to generated number");
        System.out.println("\n\n**************   Let's start the game **************");

        
        int choice = 1 ;
        int round = 1 ;
        while(choice != 0 && round<=3)
        {

            System.out.println("\n********************** ROUND" + round + "  *****************************\n");
            int randInt = rand.nextInt(100) + 1;

            int attempts = 1 ;
            while(attempts <= 5)
            {
                System.out.print("Enter number attempt " + attempts + " : " ); 
                int n = sc.nextInt();
                

                int diff = n - randInt ;
 
                if(diff<0)
                {
                    diff = diff * -1 ;
                }

                    if(diff>=40)
                    {
                        System.out.println("you are too far from generated number");
                    }
                    else if(diff < 40 && diff >= 10)
                    {
                        System.out.println("you are neither too close nor too far from generated number");
                    }
                    else if(diff < 10 && diff > 0)
                    {
                        System.out.println("you are too close to generated number");
                    }
                    else if(diff == 0)
                    {
                        System.out.println("COngratulations !! You have guessed a number ");
                        if(round == 1)
                        {
                            score1++ ;
                        }
                        else if(round == 2)
                        {
                            score2++ ;
                        }
                        else if(round == 3)
                        {
                            score3++ ;
                        }
                        attempts = 6 ;
                    }

                attempts++ ;
            }

            System.out.println("Generated number : "+randInt);

            round++ ;
        }

        System.out.println("\n\n****************** Result ********************");
        System.out.println("Score in Round 1 : "+score1);
        System.out.println("Score in Round 2 : "+score2);
        System.out.println("Score in Round 3 : "+score3);
        System.out.println("Total Score = " + (score1+score2+score3));
        System.out.println("************************************************");

        sc.close();
    }
}